app:
  title: CPLABS Backstage APP
  baseUrl: ${FRONTEND_BASE_URL}

organization:
  name: Cplabs

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    port: 7007
    host: 0.0.0.0
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: ${FRONTEND_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    # client: better-sqlite3
    # connection: ':memory:'
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

    auditor:
    severityLogLevelMappings:
      low: debug # 문제 해결용
      medium: debug # 정상 작업 확인
      high: warn # 문제 상황 알림
      critical: error # 심각한 문제
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  bitbucketCloud:
    - username: ${BITBUCKET_CLOUD_USERNAME}
      appPassword: ${BITBUCKET_CLOUD_APP_PASSWORD}

      # This is a Bitbucket Cloud App Password, you can find out how to generate this token, and more information
      # about setting up the Bitbucket Cloud integration here: https://backstage.io/docs/integrations/bitbucket-cloud/locations#configuration
  # github:
  #   - host: github.com
  #     # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
  #     # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
  #     token: ${GITHUB_TOKEN}
  #   ### Example for how to add your GitHub Enterprise instance using the API:
  #   # - host: ghe.example.net
  #   #   apiBaseUrl: https://ghe.example.net/api/v3
  #   #   token: ${GHE_TOKEN}

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  environment: development
  providers:
    # guest:
    #   dangerouslyAllowOutsideDevelopment: true  //게스트 로그인 허용
    google:
      development:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
        # uncomment to set lifespan of user session
        # sessionDuration: { hours: 24 } # supports `ms` library format (e.g. '24h', '2 days'), ISO duration, "human duration" as used in code
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/google/provider#resolvers for more resolvers
            - resolver: emailLocalPartMatchingUserEntityName
  autologout:
    enabled: true

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

## 웹훅 임시 주석(public IP없음)
# events:
#   http:
#     topics:
#       - bitbucketCloud
#   modules:
#     bitbucketCloud:
#       webhookSecret: ${BITBUCKET_WEBHOOK_SECRET}

catalog:
  # import:
  #   entityFilename: catalog-info.yaml
  #   pullRequestBranchName: backstage-integration
  processingInterval: { minutes: 30 }
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User, Template]
  locations:
    - type: file
      target: ../../catalogs/entities.yaml

    - type: file
      target: ../../catalogs/org/groups.yaml
      rules:
        - allow: [Group]

    - type: file
      target: ../../catalogs/org/users/developers.yaml
      rules:
        - allow: [User]

    - type: file
      target: ../../catalogs/template/template.yaml
      rules:
        - allow: [Template]
  useUrlReadersSearch: true

  providers:
    bitbucketCloud:
      yourProviderId:
        workspace: coinplugin
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 3 }

kubernetes:
  # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: false
