services:
  postgres:
    image: postgres:17.0-bookworm
    env_file:
      - .env
    ports:
      - 5432:5432

  # 메인 Backstage 서비스
  backstage:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '7007:7007'
    # volumes:
    #   - .:/app  # 실시간 코드 반영
    #   - /app/node_modules  # node_modules 보호
    depends_on:
      - postgres
volumes:
  postgres_data:
