services:
  postgres:
    image: postgres:17.0-bookworm
    env_file:
      - .env
    ports:
      - 5432:5432

  backstage:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3001:7007'
      - '7007:7007'
    depends_on:
      - postgres

volumes:
  postgres_data:
