apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: ai-solution-dev-2
  type: service

  parameters:
    - title: Fill in repository details
      required:
        - component_id
        - owner
        - workspace
        - projectKey
      properties:
        component_id:
          title: Repository Name
          type: string
          description: Unique name of the new repository
          ui:autofocus: true
          # 고유성을 위한 패턴 추가
          pattern: '^[a-z0-9-]+$'
        owner: # <-- owner 파라미터 정의 추가
          title: Owner
          type: string
          description: Owner of the component. Must be a registered user or group in the catalog.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        workspace:
          title: Bitbucket Workspace
          type: string
          description: The ID of the Bitbucket Workspace where the repository will be created.
          default: 'coinplugin'
        projectKey:
          title: Bitbucket Project Key
          type: string
          description: The key of the Bitbucket project (e.g., 'PROJ').
          enum:
            - 'DEVOPS'
            - 'REC'
            - 'ECO'
        description:
          title: Description
          type: string
          description: A description for the new repository.

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }} # <-- owner 값을 content에 전달

    - id: publish
      name: Publish
      action: publish:bitbucketCloud
      input:
        repoUrl: bitbucket.org?workspace=${{ parameters.workspace }}&project=${{ parameters.projectKey }}&repo=${{ parameters.component_id }}
        description: ${{ parameters.description }}
        defaultBranch: 'main'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        # 선택적: 기존 엔트리가 있으면 업데이트
        optional: true

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
