---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: CPLABS
  description: All CPLABS employees
spec:
  type: organization
  children:
    [
      AI Solution Dev 1,
      AI Solution Dev 2,
      Service Dev 1,
      Service Dev 2,
      Daepa Dev,
      LAB,
    ]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: AI Solution Dev 1
  description: AI Solution Dev 1 team
spec:
  namespace: labatory
  type: team
  parent: CPLABS
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: AI Solution Dev 2
  description: AI Solution Dev 2 team
spec:
  namespace: labatory
  type: team
  parent: CPLABS
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Service Dev 1
  description: Service Dev 1 team
spec:
  namespace: labatory
  type: team
  parent: CPLABS
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Service Dev 2
  description: Service Dev 2 team
spec:
  namespace: labatory
  type: team
  parent: CPLABS
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: DaePa Dev
  description: DaePa Dev team
spec:
  namespace: labatory
  type: team
  parent: CPLABS
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: LAB
  description: LABATORY
spec:
  namespace: labatory
  type: team
  parent: CPLABS
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: managers
  description: Management team
spec:
  type: team
  parent: CPLABS
  children: [engineering-managers, product-managers, executives]

---
# 관리팀 하위 그룹들
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering-managers
  description: Engineering managers
spec:
  type: role
  parent: managers

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: product-managers
  description: Product managers
spec:
  type: role
  parent: managers

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: executives
  description: Executive team
spec:
  type: role
  parent: managers
