apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
spec:
  type: service
  lifecycle: dev
  owner: ${{ values.owner }} # <-- 전달받은 owner 값을 사용
