apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
spec:
  type: service
  owner: ai-solution-dev-2 # user:guest → ai-solution-dev-2 (적절한 그룹으로 변경)
  lifecycle: experimental
